
package com.agritsik.samples.boundary.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductWS", targetNamespace = "http://boundary.samples.agritsik.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "welcomeMessage", targetNamespace = "http://boundary.samples.agritsik.com/", className = "com.agritsik.samples.boundary.ws.WelcomeMessage")
    @ResponseWrapper(localName = "welcomeMessageResponse", targetNamespace = "http://boundary.samples.agritsik.com/", className = "com.agritsik.samples.boundary.ws.WelcomeMessageResponse")
    @Action(input = "http://boundary.samples.agritsik.com/ProductWS/welcomeMessageRequest", output = "http://boundary.samples.agritsik.com/ProductWS/welcomeMessageResponse")
    public String welcomeMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.agritsik.samples.boundary.ws.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://boundary.samples.agritsik.com/", className = "com.agritsik.samples.boundary.ws.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://boundary.samples.agritsik.com/", className = "com.agritsik.samples.boundary.ws.FindResponse")
    @Action(input = "http://boundary.samples.agritsik.com/ProductWS/findRequest", output = "http://boundary.samples.agritsik.com/ProductWS/findResponse")
    public Product find(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://boundary.samples.agritsik.com/", className = "com.agritsik.samples.boundary.ws.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://boundary.samples.agritsik.com/", className = "com.agritsik.samples.boundary.ws.CreateResponse")
    @Action(input = "http://boundary.samples.agritsik.com/ProductWS/createRequest", output = "http://boundary.samples.agritsik.com/ProductWS/createResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

}
